ALTER TABLE receipts ADD COLUMN IF NOT EXISTS gr_number VARCHAR(255);
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS material VARCHAR(255);
ALTER TABLE receipts ADD COLUMN IF NOT EXISTS charges DOUBLE PRECISION NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS ix_receipts_gr_number ON receipts (gr_number);
